# Generated by Django 5.2.6 on 2025-09-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField()),
                ('car_brand', models.CharField()),
                ('release_date', models.DateField()),
                ('car_color', models.CharField()),
            ],
        ),
    ]
